// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package reverse_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReverseInteractClient is the client API for ReverseInteract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseInteractClient interface {
	GetCommand(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Command, error)
	HandsOn(ctx context.Context, opts ...grpc.CallOption) (ReverseInteract_HandsOnClient, error)
}

type reverseInteractClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseInteractClient(cc grpc.ClientConnInterface) ReverseInteractClient {
	return &reverseInteractClient{cc}
}

func (c *reverseInteractClient) GetCommand(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Command, error) {
	out := new(Command)
	err := c.cc.Invoke(ctx, "/pb.ReverseInteract/GetCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseInteractClient) HandsOn(ctx context.Context, opts ...grpc.CallOption) (ReverseInteract_HandsOnClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReverseInteract_ServiceDesc.Streams[0], "/pb.ReverseInteract/HandsOn", opts...)
	if err != nil {
		return nil, err
	}
	x := &reverseInteractHandsOnClient{stream}
	return x, nil
}

type ReverseInteract_HandsOnClient interface {
	Send(*Response) error
	Recv() (*Command, error)
	grpc.ClientStream
}

type reverseInteractHandsOnClient struct {
	grpc.ClientStream
}

func (x *reverseInteractHandsOnClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reverseInteractHandsOnClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReverseInteractServer is the server API for ReverseInteract service.
// All implementations must embed UnimplementedReverseInteractServer
// for forward compatibility
type ReverseInteractServer interface {
	GetCommand(context.Context, *Response) (*Command, error)
	HandsOn(ReverseInteract_HandsOnServer) error
	mustEmbedUnimplementedReverseInteractServer()
}

// UnimplementedReverseInteractServer must be embedded to have forward compatible implementations.
type UnimplementedReverseInteractServer struct {
}

func (UnimplementedReverseInteractServer) GetCommand(context.Context, *Response) (*Command, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommand not implemented")
}
func (UnimplementedReverseInteractServer) HandsOn(ReverseInteract_HandsOnServer) error {
	return status.Errorf(codes.Unimplemented, "method HandsOn not implemented")
}
func (UnimplementedReverseInteractServer) mustEmbedUnimplementedReverseInteractServer() {}

// UnsafeReverseInteractServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseInteractServer will
// result in compilation errors.
type UnsafeReverseInteractServer interface {
	mustEmbedUnimplementedReverseInteractServer()
}

func RegisterReverseInteractServer(s grpc.ServiceRegistrar, srv ReverseInteractServer) {
	s.RegisterService(&ReverseInteract_ServiceDesc, srv)
}

func _ReverseInteract_GetCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseInteractServer).GetCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReverseInteract/GetCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseInteractServer).GetCommand(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseInteract_HandsOn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReverseInteractServer).HandsOn(&reverseInteractHandsOnServer{stream})
}

type ReverseInteract_HandsOnServer interface {
	Send(*Command) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type reverseInteractHandsOnServer struct {
	grpc.ServerStream
}

func (x *reverseInteractHandsOnServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reverseInteractHandsOnServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReverseInteract_ServiceDesc is the grpc.ServiceDesc for ReverseInteract service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverseInteract_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ReverseInteract",
	HandlerType: (*ReverseInteractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommand",
			Handler:    _ReverseInteract_GetCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandsOn",
			Handler:       _ReverseInteract_HandsOn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ghost.proto",
}
